# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Set up SSH
        run: |
          # Assuming gizzmo-key is stored at ~/.ssh/gizzmo-key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          # Set up the SSH key
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/gizzmos-key
          chmod 600 ~/.ssh/gizzmo-key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/gizzmo-key

      - name: Update repository to use SSH
        run: |
          cd /var/www/Gizzmos
          git remote set-url origin git@github.com:Griffinov22/Gizzmos-E-commerce.git

      - name: Pull latest changes from main branch
        run: |
          cd /var/www/Gizzmos
          git pull origin main
